### PR TITLE
Adding in UserType to dashboard table

### PR DESCRIPTION
**Pull request by jamiepollock**
As referenced in request #2.

Feel free to comment on the use of the whole `UserType` object rather than simply `UserType.Name`. I wasn't overly happy with it and can for now reduce it to just the name was thinking for the future with #3. Although that could change and I'm really not a fan of sending back too much data. :pensive:

### CODE REVIEW

**Comment by jamiepollock** [comment]
Actually decided to change it in [23d8c41](https://github.com/leekelleher/umbraco-bulk-user-admin/pull/4/commits/23d8c413e476cdc6ba36bbb467b7cbc333a7c249). Couldn't stand passing that much unused data to the view.

**Comment by leekelleher** [comment]
@jamiepollock I'm happy with only the UserType name being sent/displayed.

Are you happy with me merging in your PR now?

**Comment by jamiepollock** [comment]
@leekelleher Yea, definitely if you're happy with this. It didn't make sense to have the whole object being brought back - it felt wrong :)

**Comment by leekelleher** [comment]
Groovy, thanks @jamiepollock!

**Comment by jamiepollock** [comment]
@leekelleher Thank you, sir!

**Pull request merged**
