### PR TITLE
Refactored the filter + pagination support

### PR DESCRIPTION
**Pull request by leekelleher**
Whilst testing, I found that the combination of filtering and pagination didn't work.

The call to `UserService.GetAll` was pre-paginating the user list results before we could filter them.
Now we can get all the users first, then filter accordingly. Depending on performance, we may need to temporarily cache the users to save repeated database hits (in quick succession).

With refactoring the filtering method, I found it tricky to debug the previous Linq/Func expression, so opted to try using the `yield returns` approach. **This is totally open for discussion.**

Removed the `BulkUserListItemModel` class, as we no longer explicitly need it.

Added support for a custom `PageSize` by checking for an AppSetting key, (which we need to document).

### CODE REVIEW

**Comment by jamiepollock** [comment]
@leekelleher I saw your commits - sorry about this :/

Also wanted to talk about updating the layout after [this issue](https://github.com/jamiepollock/Umbraco-Nuget-Package-Dashboard/issues/2) was raised in another project. It shouldn't affect the work done here as it will be FE changes.

What do you think?

**Comment by leekelleher** [comment]
@jamiepollock No need to apologise at all, it's all progress :rocket: 

I'll take a read of the other ticket.

**Comment by leekelleher** [comment]
I did actually have a play around with moving the filter bar to be above the table, but I couldn't settle on a position that I liked.  Then I looked at the native ListView control and the filter was in the table, so kept it as is.

Totally open to suggestions on re-positioning it.

**Comment by jamiepollock** [comment]
I think I like how I settled on things in the other ticket, but it's entirely subjective.

I think possibly adding the "Update" button to top left with the toggle counter like in the [7.4.x+ list view](https://cloud.githubusercontent.com/assets/2919859/16777814/68cc5dcc-486b-11e6-8f50-c5f3404ceb0a.png) would be the way I'd go with it personally.

The only issue with taking on styling from newer versions of Umbraco is backward compatibility. Although there was discussion that Umbraco Forms possibly uses CMS versioning to work out what components should be used but that could get messy to manage.

**Comment by leekelleher** [comment]
I'm :100:% on making the stylings as consistent with Umbraco!

My only gotcha is that on Carlsberg we're currently stuck on v7.2.8, so that's our base requirement at the moment :disappointed: 

Still, I don't want that to hold up any package development, so we can always create a new branch for these types of improvements.

**Comment by jamiepollock** [comment]
Completely understand, The way I handled it was adding in styles from Umbraco which are targeted using the containing class although, that could be open to headache in the future...

https://github.com/jamiepollock/Umbraco-Nuget-Package-Dashboard/commit/e50a0ebf6c2c015c2bea4d68af93e8e5088f2e45

**Pull request merged**
