### PR TITLE
Refresh UI using umb-* directives

### PR DESCRIPTION
**Pull request by jamiepollock**
Moving discussion from #12 & #14 into this PR. I've moved a lot of the UI into using umb-* directives. This took a lot of refactoring so take your time looking through the code!

Let me know any thoughts or feedback.

### CODE REVIEW

**Comment by jamiepollock** [comment]
Also umb-overlay as mentioned in [commit 800deec](https://github.com/leekelleher/umbraco-bulk-user-admin/pull/17/commits/800deecb1519ab44c566c3eb7745b083cc0448b6) there seems to be an issue with ng-dirty properties after the umb-overlay has been closed. This doesn't occur with dialogService dialogs but they don't fade out the background like an umb-overlay does.

**Comment by leekelleher** [comment]
@jamiepollock Cool! _Doubt I'll have time this week to review any code, (heavy work load at the moment)._

**Comment by jamiepollock** [comment]
@leekelleher no worries, chap! There are so many changes made to accommodate the umb-* directives it'll need a look over at some point.

If you have any thoughts @mattbrailsford and @bjarnef I'd really appreciate it!

**Comment by bjarnef** [comment]
@jamiepollock for the disappearing "active" icon on hover, we need to fix this in core.

https://github.com/umbraco/Umbraco-CMS/blob/2d6b8712d5c220b3bdeb71e1cd52871ca9095df8/src/Umbraco.Web.UI.Client/src/less/listview.less#L246-L249

I think this can just be removed in core and then instead toggle a "hidden" class, when selecting a row - since it then display a checkmark font icon and hide the checkbox.

For now I think you need to include a css rule to force the icons to be visible. E.g. something like:
```
.bua--dashboard .umb-listview .table-striped tbody i,
.bua--dashboard .umb-listview .table-striped tbody i:hover {
  display: inline-block !important;
}
```

**Comment by jamiepollock** [comment]
@bjarnef not sure this is still relevant? As Active is just the "ToString()" of the Boolean now it's using list-view.

Here's a couple of screengrabs of the newly implemented stuff.

bua-umb-directives-search
bua-umb-directives-selected

**Comment by jamiepollock** [comment]
Speaking of which, I should probably should remove most of the CSS...

**Comment by bjarnef** [comment]
@jamiepollock regarding the flickering "active" icon on hover before it was affected by these lines:
https://github.com/umbraco/Umbraco-CMS/blob/2d6b8712d5c220b3bdeb71e1cd52871ca9095df8/src/Umbraco.Web.UI.Client/src/less/listview.less#L246-L249

I had originally modified, because it affected the "handle" in e.g. related links property editor (which is a table).
Here you can see how it original affected all icons (which used `<i>` element)
https://github.com/umbraco/Umbraco-CMS/commit/7cf4c33d1541e1ad8536c14de30f78d9d4621120

and originally I think the listview was switching between the icon and a checkbox on hover, which was why it hide the icon on hover - but it also affected all other icons in the table.

In the updated listview I am not sure if you can render the output different than raw text - maybe with a custom listview layout? http://24days.in/umbraco-cms/2016/custom-list-view-layouts/ .. but when using `umb-table` I am not sure how much you can modify it - replacing the  the true value with `<i class="icon icon-check color-green"></i>` in the controller will probably render it as raw text?

**Comment by leekelleher** [comment]
@jamiepollock I was looking over my project's open PRs, and had forgot about this one, (sorry).

**What did you like to do with it?** Given that Umbraco v7.7 has a refreshed Users section. (Also there is currently a merge-conflict with the PR - if you wanted to rebase it?)

**Comment by jamiepollock** [comment]
@leekelleher that's a fair point. The UI of Umbraco has changed a fair bit since this PR was created.

It's not entirely without merit keeping it around for pre-7.7 Umbraco apps but definitely feels like an bit of a oddity now.

I'm happy to close this PR unless we're considering a post 7.7 version, if that's even needed. 

I'll be honest I've not looked at v7.7's User updates.

**Comment by leekelleher** [comment]
@jamiepollock I'm archiving this project, so closing off your PR.
Thanks again for all your help with it a few years ago! 🥇

**Pull request closed without merging**
