### PR TITLE
Added new Additional Features section to README.md

### PR DESCRIPTION
**Pull request by jamiepollock**
Feel free to restructure this, this is just to get the ball rolling on a new branch.

### CODE REVIEW

**Comment by leekelleher** [comment]
I've moved the Features part higher up the README.
Added in bits about package download and NuGet too.

I'll get the screengrab(s) updated, then I think we're ready to rock on the docs front.

**Comment by jamiepollock** [comment]
@leekelleher fantastic! This is shaping up nicely :)

**Comment by leekelleher** [comment]
Re-opening, as the branch hadn't been merged in yet.

**Comment by leekelleher** [comment]
Finally got around to catching up on this project; merged in.

**Pull request merged**
